######################################################################
# This playbook populates the known_hosts file with all the active
# nodes so that we don't have to verify the authenticity of each node
# upon the first run of ansible.
######################################################################
---
- name: Make sure known_hosts file exists
  stat: "path={{ ssh_known_hosts_file }}"
  register: known_hosts_exists

- name: Create known_hosts file if it doesnt exist
  file: "path={{ ssh_known_hosts_file }} state=touch"
  when: known_hosts_exists.stat.exists == False

- name: Check host name availability
  shell: "ssh-keygen -f {{ ssh_known_hosts_file }} -F {{ item }}"
  with_items: ssh_known_hosts
  register: ssh_known_host_results
  ignore_errors: yes

- name: Scan the public key
  shell: "{{ ssh_known_hosts_command}} {{ item.item }} >> {{ ssh_known_hosts_file }}"
  with_items: ssh_known_host_results.results
  when: item.stdout == ""
