#################################################################
# Generate the private keys to establish trusted host connection
# so that we are not required to use password for ansible
# execution on the nodes.
#################################################################

---
# Make sure SSH Keys are present in the mgmt node
- name: Generate pulic and private keys SSH Keys
  user: name=vagrant
        generate_ssh_key=yes
        ssh_key_bits=2048
